### ISSUE TITLE
Immediate operands size bugfix

### ISSUE THREAD

**Issue by ghost** [mcalha/jasmin#8]
Ao abrir um ficheiro com bastantes linhas de código recebo um arrayIndexOutOfBoundsException depois deste bugfix, ao pôr o código em comentário a excepção deixa de ser lançada.

**Comment by ulissesferreira** [comment]
O problema já está resolvido colegas?

**Comment by ghost** [comment]
Em princípio sim. Se encontrarem mais bugs que precisarem que nós
resolvamos, avisem
